/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
/** A simple name (attribute) and no namespace attribute: inherit the null namespace of the enclosing type 'Example'. The fullname is 'Simple'. */
@org.apache.avro.specific.AvroGenerated
public enum Simple implements org.apache.avro.generic.GenericEnumSymbol<Simple> {
  a, b  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Simple\",\"doc\":\"A simple name (attribute) and no namespace attribute: inherit the null namespace of the enclosing type 'Example'. The fullname is 'Simple'.\",\"symbols\":[\"a\",\"b\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
