/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package a.full;
/** A simple name (attribute) and no namespace attribute: inherit the namespace of the enclosing type 'a.full.Name'. The fullname is 'a.full.Understanding'. */
@org.apache.avro.specific.AvroGenerated
public enum Understanding implements org.apache.avro.generic.GenericEnumSymbol<Understanding> {
  d, e  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Understanding\",\"namespace\":\"a.full\",\"doc\":\"A simple name (attribute) and no namespace attribute: inherit the namespace of the enclosing type 'a.full.Name'. The fullname is 'a.full.Understanding'.\",\"symbols\":[\"d\",\"e\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
