/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.injavawetrust.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ComplexTypes extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8452000714110236646L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ComplexTypes\",\"namespace\":\"com.injavawetrust.dto\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"favorite_number\",\"type\":[\"int\",\"null\"]},{\"name\":\"parameters\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"suit\",\"type\":{\"type\":\"enum\",\"name\":\"Suit2\",\"symbols\":[\"SPADES\",\"HEARTS\",\"DIAMONDS\",\"CLUBS\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ComplexTypes> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ComplexTypes> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ComplexTypes> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ComplexTypes> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ComplexTypes> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ComplexTypes to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ComplexTypes from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ComplexTypes instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ComplexTypes fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence name;
  private java.lang.Integer favorite_number;
  private java.util.List<java.lang.CharSequence> parameters;
  private com.injavawetrust.dto.Suit2 suit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ComplexTypes() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param favorite_number The new value for favorite_number
   * @param parameters The new value for parameters
   * @param suit The new value for suit
   */
  public ComplexTypes(java.lang.CharSequence name, java.lang.Integer favorite_number, java.util.List<java.lang.CharSequence> parameters, com.injavawetrust.dto.Suit2 suit) {
    this.name = name;
    this.favorite_number = favorite_number;
    this.parameters = parameters;
    this.suit = suit;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return favorite_number;
    case 2: return parameters;
    case 3: return suit;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: favorite_number = (java.lang.Integer)value$; break;
    case 2: parameters = (java.util.List<java.lang.CharSequence>)value$; break;
    case 3: suit = (com.injavawetrust.dto.Suit2)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'favorite_number' field.
   * @return The value of the 'favorite_number' field.
   */
  public java.lang.Integer getFavoriteNumber() {
    return favorite_number;
  }


  /**
   * Sets the value of the 'favorite_number' field.
   * @param value the value to set.
   */
  public void setFavoriteNumber(java.lang.Integer value) {
    this.favorite_number = value;
  }

  /**
   * Gets the value of the 'parameters' field.
   * @return The value of the 'parameters' field.
   */
  public java.util.List<java.lang.CharSequence> getParameters() {
    return parameters;
  }


  /**
   * Sets the value of the 'parameters' field.
   * @param value the value to set.
   */
  public void setParameters(java.util.List<java.lang.CharSequence> value) {
    this.parameters = value;
  }

  /**
   * Gets the value of the 'suit' field.
   * @return The value of the 'suit' field.
   */
  public com.injavawetrust.dto.Suit2 getSuit() {
    return suit;
  }


  /**
   * Sets the value of the 'suit' field.
   * @param value the value to set.
   */
  public void setSuit(com.injavawetrust.dto.Suit2 value) {
    this.suit = value;
  }

  /**
   * Creates a new ComplexTypes RecordBuilder.
   * @return A new ComplexTypes RecordBuilder
   */
  public static com.injavawetrust.dto.ComplexTypes.Builder newBuilder() {
    return new com.injavawetrust.dto.ComplexTypes.Builder();
  }

  /**
   * Creates a new ComplexTypes RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ComplexTypes RecordBuilder
   */
  public static com.injavawetrust.dto.ComplexTypes.Builder newBuilder(com.injavawetrust.dto.ComplexTypes.Builder other) {
    if (other == null) {
      return new com.injavawetrust.dto.ComplexTypes.Builder();
    } else {
      return new com.injavawetrust.dto.ComplexTypes.Builder(other);
    }
  }

  /**
   * Creates a new ComplexTypes RecordBuilder by copying an existing ComplexTypes instance.
   * @param other The existing instance to copy.
   * @return A new ComplexTypes RecordBuilder
   */
  public static com.injavawetrust.dto.ComplexTypes.Builder newBuilder(com.injavawetrust.dto.ComplexTypes other) {
    if (other == null) {
      return new com.injavawetrust.dto.ComplexTypes.Builder();
    } else {
      return new com.injavawetrust.dto.ComplexTypes.Builder(other);
    }
  }

  /**
   * RecordBuilder for ComplexTypes instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ComplexTypes>
    implements org.apache.avro.data.RecordBuilder<ComplexTypes> {

    private java.lang.CharSequence name;
    private java.lang.Integer favorite_number;
    private java.util.List<java.lang.CharSequence> parameters;
    private com.injavawetrust.dto.Suit2 suit;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.injavawetrust.dto.ComplexTypes.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.favorite_number)) {
        this.favorite_number = data().deepCopy(fields()[1].schema(), other.favorite_number);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.parameters)) {
        this.parameters = data().deepCopy(fields()[2].schema(), other.parameters);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.suit)) {
        this.suit = data().deepCopy(fields()[3].schema(), other.suit);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing ComplexTypes instance
     * @param other The existing instance to copy.
     */
    private Builder(com.injavawetrust.dto.ComplexTypes other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.favorite_number)) {
        this.favorite_number = data().deepCopy(fields()[1].schema(), other.favorite_number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.parameters)) {
        this.parameters = data().deepCopy(fields()[2].schema(), other.parameters);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.suit)) {
        this.suit = data().deepCopy(fields()[3].schema(), other.suit);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.injavawetrust.dto.ComplexTypes.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.injavawetrust.dto.ComplexTypes.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'favorite_number' field.
      * @return The value.
      */
    public java.lang.Integer getFavoriteNumber() {
      return favorite_number;
    }


    /**
      * Sets the value of the 'favorite_number' field.
      * @param value The value of 'favorite_number'.
      * @return This builder.
      */
    public com.injavawetrust.dto.ComplexTypes.Builder setFavoriteNumber(java.lang.Integer value) {
      validate(fields()[1], value);
      this.favorite_number = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'favorite_number' field has been set.
      * @return True if the 'favorite_number' field has been set, false otherwise.
      */
    public boolean hasFavoriteNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'favorite_number' field.
      * @return This builder.
      */
    public com.injavawetrust.dto.ComplexTypes.Builder clearFavoriteNumber() {
      favorite_number = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'parameters' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getParameters() {
      return parameters;
    }


    /**
      * Sets the value of the 'parameters' field.
      * @param value The value of 'parameters'.
      * @return This builder.
      */
    public com.injavawetrust.dto.ComplexTypes.Builder setParameters(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.parameters = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'parameters' field has been set.
      * @return True if the 'parameters' field has been set, false otherwise.
      */
    public boolean hasParameters() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'parameters' field.
      * @return This builder.
      */
    public com.injavawetrust.dto.ComplexTypes.Builder clearParameters() {
      parameters = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'suit' field.
      * @return The value.
      */
    public com.injavawetrust.dto.Suit2 getSuit() {
      return suit;
    }


    /**
      * Sets the value of the 'suit' field.
      * @param value The value of 'suit'.
      * @return This builder.
      */
    public com.injavawetrust.dto.ComplexTypes.Builder setSuit(com.injavawetrust.dto.Suit2 value) {
      validate(fields()[3], value);
      this.suit = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'suit' field has been set.
      * @return True if the 'suit' field has been set, false otherwise.
      */
    public boolean hasSuit() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'suit' field.
      * @return This builder.
      */
    public com.injavawetrust.dto.ComplexTypes.Builder clearSuit() {
      suit = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ComplexTypes build() {
      try {
        ComplexTypes record = new ComplexTypes();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.favorite_number = fieldSetFlags()[1] ? this.favorite_number : (java.lang.Integer) defaultValue(fields()[1]);
        record.parameters = fieldSetFlags()[2] ? this.parameters : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[2]);
        record.suit = fieldSetFlags()[3] ? this.suit : (com.injavawetrust.dto.Suit2) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ComplexTypes>
    WRITER$ = (org.apache.avro.io.DatumWriter<ComplexTypes>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ComplexTypes>
    READER$ = (org.apache.avro.io.DatumReader<ComplexTypes>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    if (this.favorite_number == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeInt(this.favorite_number);
    }

    long size0 = this.parameters.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.parameters) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeEnum(this.suit.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      if (in.readIndex() != 0) {
        in.readNull();
        this.favorite_number = null;
      } else {
        this.favorite_number = in.readInt();
      }

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.parameters;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("parameters").schema());
        this.parameters = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

      this.suit = com.injavawetrust.dto.Suit2.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.favorite_number = null;
          } else {
            this.favorite_number = in.readInt();
          }
          break;

        case 2:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.parameters;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("parameters").schema());
            this.parameters = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        case 3:
          this.suit = com.injavawetrust.dto.Suit2.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










